"""
LedgerLens — evaluation deck generator.

Every diagram is built from native PowerPoint vector shapes: no raster images,
nothing generated by an image model, nothing that goes soft on a projector.
Open the .pptx and any box, arrow or label can be edited in place.

Design system is the same one the product uses — "Forensic Ledger":
deep ink ground, warm off-white type, one gold for money, one burnt red for
risk, one green for recovered. A colour never means two things.
"""
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE, MSO_CONNECTOR

# ── palette ────────────────────────────────────────────────────────────────
INK       = RGBColor(0x0A, 0x0B, 0x0D)
PANEL     = RGBColor(0x12, 0x14, 0x17)
PANEL2    = RGBColor(0x19, 0x1C, 0x21)
LINE      = RGBColor(0x26, 0x2A, 0x31)
LINE_SOFT = RGBColor(0x1B, 0x1E, 0x23)
PAPER     = RGBColor(0xE9, 0xE5, 0xDC)
PAPER_DIM = RGBColor(0xA8, 0xA4, 0x98)
MUTED     = RGBColor(0x6E, 0x70, 0x79)
GOLD      = RGBColor(0xC9, 0xA2, 0x27)
GOLD_SOFT = RGBColor(0x8A, 0x72, 0x20)
SIGNAL    = RGBColor(0xC4, 0x50, 0x3A)
SIGNAL_DIM= RGBColor(0x7A, 0x32, 0x26)
VERIFY    = RGBColor(0x5B, 0x8F, 0x6E)
SLATE     = RGBColor(0x6B, 0x83, 0x94)
CLAY      = RGBColor(0xA8, 0x70, 0x5A)

# Fonts chosen for machines you don't control: Georgia and Consolas ship with
# Windows and with Office on macOS; Segoe UI is the Windows system face.
DISPLAY, SANS, MONO = "Georgia", "Segoe UI", "Consolas"

W, H = 13.333, 7.5
M = 0.72                      # page margin
prs = Presentation()
prs.slide_width, prs.slide_height = Inches(W), Inches(H)


# ── primitives ─────────────────────────────────────────────────────────────
def _noshadow(shp):
    shp.shadow.inherit = False
    return shp

def rect(s, x, y, w, h, fill=None, line=None, lw=0.75, shape=MSO_SHAPE.RECTANGLE):
    sh = s.shapes.add_shape(shape, Inches(x), Inches(y), Inches(w), Inches(h))
    if fill is None:
        sh.fill.background()
    else:
        sh.fill.solid(); sh.fill.fore_color.rgb = fill
    if line is None:
        sh.line.fill.background()
    else:
        sh.line.color.rgb = line; sh.line.width = Pt(lw)
    sh.text_frame.text = ""
    return _noshadow(sh)

def hline(s, x, y, w, color=LINE, lw=0.75):
    c = s.shapes.add_connector(MSO_CONNECTOR.STRAIGHT, Inches(x), Inches(y), Inches(x + w), Inches(y))
    c.line.color.rgb = color; c.line.width = Pt(lw)
    return _noshadow(c)

def vline(s, x, y, h, color=LINE, lw=0.75):
    c = s.shapes.add_connector(MSO_CONNECTOR.STRAIGHT, Inches(x), Inches(y), Inches(x), Inches(y + h))
    c.line.color.rgb = color; c.line.width = Pt(lw)
    return _noshadow(c)

from pptx.oxml.ns import qn
import copy

def _tail_arrow(conn):
    """Native DrawingML arrowhead — renders correctly in PowerPoint, Keynote,
    Google Slides and LibreOffice, unlike a hand-drawn triangle."""
    ln = conn.line._get_or_add_ln()
    for tag in ("a:tailEnd",):
        e = ln.find(qn(tag))
        if e is not None:
            ln.remove(e)
    end = ln.makeelement(qn("a:tailEnd"), {"type": "triangle", "w": "sm", "len": "sm"})
    ln.append(end)
    return conn

def arrow(s, x, y, w, color=PAPER_DIM, lw=1.0):
    return _tail_arrow(hline(s, x, y, w, color, lw))

def down_arrow(s, x, y, h, color=PAPER_DIM, lw=1.0):
    return _tail_arrow(vline(s, x, y, h, color, lw))

def text(s, x, y, w, h, runs, size=13, font=SANS, color=PAPER, bold=False,
         align=PP_ALIGN.LEFT, spacing=1.28, anchor=MSO_ANCHOR.TOP, space_after=0,
         caps=False):
    """runs: a string, or a list of (text, {overrides}) tuples, or a list of
    paragraphs where each paragraph is itself such a list."""
    tb = s.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = tb.text_frame
    tf.word_wrap = True
    tf.margin_left = tf.margin_right = tf.margin_top = tf.margin_bottom = 0
    tf.vertical_anchor = anchor

    paras = runs if isinstance(runs, list) and runs and isinstance(runs[0], list) else [runs]
    for i, para in enumerate(paras):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.alignment = align
        p.line_spacing = spacing
        p.space_after = Pt(space_after)
        items = para if isinstance(para, list) else [(para, {})]
        for item in items:
            t, ov = item if isinstance(item, tuple) else (item, {})
            if ov.get("caps", caps):
                t = t.upper()
            # A literal \n inside a run is not a line break in DrawingML —
            # PowerPoint would render it as one long wrapped line. Emit real
            # <a:br/> elements instead.
            for j, seg in enumerate(t.split("\n")):
                if j:
                    p.add_line_break()
                r = p.add_run()
                r.text = seg
                f = r.font
                f.name = ov.get("font", font)
                f.size = Pt(ov.get("size", size))
                f.bold = ov.get("bold", bold)
                f.color.rgb = ov.get("color", color)
    return tb

def kicker(s, x, y, t, color=MUTED, size=9.5):
    # letterspacing isn't exposed by python-pptx; thin spaces read the same way
    return text(s, x, y, 8, 0.22, " ".join(t.upper()), size=size, font=MONO, color=color)

def chip(s, x, y, t, color=GOLD, w=None, size=8.5):
    w = w or (0.115 * len(t) + 0.24)
    r = rect(s, x, y, w, 0.235, None, color, 0.6, MSO_SHAPE.ROUNDED_RECTANGLE)
    r.adjustments[0] = 0.5
    text(s, x, y + 0.045, w, 0.2, t.upper(), size=size, font=MONO, color=color, align=PP_ALIGN.CENTER)
    return r


# ── slide chrome ───────────────────────────────────────────────────────────
ASSETS = "assets"

def new_slide(num=None, kick=None, title=None, bg="content"):
    """bg: which shader-rendered ground to lay down. These are real GLSL
    output rendered through WebGL at 2560x1440 — procedural, deterministic,
    not an image model's guess at what a background looks like."""
    s = prs.slides.add_slide(prs.slide_layouts[6])
    rect(s, 0, 0, W, H, INK)
    s.shapes.add_picture(f"{ASSETS}/bg_{bg}.jpg", 0, 0, Inches(W), Inches(H))
    top = M
    if num is not None:
        text(s, M, top, 1.2, 0.3, f"{num:02d}", size=10, font=MONO, color=MUTED)
    if kick:
        kicker(s, M + 0.62, top + 0.012, kick, GOLD)
    if title:
        text(s, M, top + 0.38, W - 2 * M, 0.6, title, size=31, font=DISPLAY, color=PAPER, spacing=1.02)
        hline(s, M, top + 1.06, W - 2 * M, LINE, 0.9)
    if num is not None:                        # footer only on numbered slides
        hline(s, M, H - 0.46, W - 2 * M, LINE_SOFT, 0.6)
        text(s, M, H - 0.37, 6, 0.24, "LedgerLens · procurement forensics",
             size=8, font=MONO, color=MUTED)
        text(s, W - M - 2, H - 0.37, 2, 0.24, f"{num:02d} / 07", size=8, font=MONO,
             color=MUTED, align=PP_ALIGN.RIGHT)
    return s

BODY_TOP = M + 1.36
FOOT = H - 0.62                                # nothing may cross this


# ══════════════════════════════════════════════════════════════════════════
# COVER
# ══════════════════════════════════════════════════════════════════════════
s = new_slide(bg="title")
text(s, M, 0.92, 6, 0.3, " ".join("LEDGERLENS"), size=11, font=MONO, color=GOLD)
text(s, M, 1.44, 9.4, 1.5,
     "An X-ray machine for\nhow a company spends.",
     size=52, font=DISPLAY, color=PAPER, spacing=0.98)
text(s, M, 3.06, 7.4, 0.62,
     "We read every invoice, purchase order and vendor record together — "
     "and show you exactly where the money is leaking.",
     size=14.5, color=PAPER_DIM, spacing=1.42)

vline(s, M, 4.04, 1.30, GOLD_SOFT, 1.6)
text(s, M + 0.26, 3.98, 6.4, 0.9, "₹18,42,650", size=54, font=DISPLAY, color=GOLD, spacing=0.95)
text(s, M + 0.30, 4.96, 7.0, 0.5,
     [[("recoverable, identified across ", {}), ("₹42.6 Cr", {"color": PAPER}),
       (" of analysed spend", {})]],
     size=12, color=PAPER_DIM)

# right rail — the corpus, stated plainly
RX = 9.05
vline(s, RX - 0.42, 1.44, 3.9, LINE, 0.9)
facts = [("5,847", "invoices analysed"), ("1,203", "purchase orders"),
         ("118", "vendors · 96 resolved entities"), ("42", "detectors across 5 pillars"),
         ("163", "findings, every one traceable"), ("94.4%", "precision on planted ground truth")]
yy = 1.44
for v, k in facts:
    text(s, RX, yy, 3.4, 0.34, v, size=19, font=MONO, color=PAPER)
    text(s, RX, yy + 0.31, 3.4, 0.28, k, size=9.5, color=MUTED)
    yy += 0.66

hline(s, M, 5.72, W - 2 * M, LINE, 0.9)
text(s, M, 5.9, 10.6, 0.4,
     "Humans review invoices one at a time. The problems only exist across thousands at once.",
     size=16, font=DISPLAY, color=GOLD)
text(s, M, 6.52, 9.0, 0.26,
     "Demo dataset — synthetic, generated for evaluation.", size=8.5, font=MONO, color=MUTED)


# ══════════════════════════════════════════════════════════════════════════
# 01 — PROBLEM STATEMENT
# ══════════════════════════════════════════════════════════════════════════
s = new_slide(1, "Problem statement",
              "Money leaks between documents, not inside them.", bg="risk")

# the four cited stakes
stats = [("5%", "of annual revenue lost to\noccupational fraud", "ACFE · Report to the Nations 2026"),
         ("0.8–2%", "of total disbursements are\nduplicate or erroneous payments", "APQC / IOFM benchmarks"),
         ("12 months", "median time a scheme runs\nbefore anyone notices", "ACFE 2026"),
         ("43%", "of frauds are found by an\nemployee tip — not by software", "ACFE 2026")]
x = M
for v, claim, src in stats:
    hline(s, x, BODY_TOP, 2.72, LINE, 0.9)
    text(s, x, BODY_TOP + 0.14, 2.72, 0.5, v, size=27, font=DISPLAY, color=SIGNAL)
    text(s, x, BODY_TOP + 0.68, 2.66, 0.66, claim, size=10.5, color=PAPER_DIM, spacing=1.32)
    text(s, x, BODY_TOP + 1.36, 2.66, 0.3, src, size=7.5, font=MONO, color=MUTED)
    x += 2.98

# ── the procurement pipeline, and the four gaps money leaves through ──
DY = BODY_TOP + 1.98
text(s, M, DY, 8, 0.28, " ".join("WHERE IT LEAVES"), size=9, font=MONO, color=MUTED)

stages = ["Requisition", "Purchase Order", "Goods Receipt", "Invoice", "Payment"]
gaps = ["no competitive\nquotes obtained", "goods never\nverified",
        "billed ≠\nordered", "paid\ntwice"]
BW, GAPW = 1.98, 0.52
SY = DY + 0.42
x = M
for i, st in enumerate(stages):
    rect(s, x, SY, BW, 0.56, PANEL, LINE, 0.9)
    text(s, x, SY + 0.17, BW, 0.3, st, size=11.5, color=PAPER, align=PP_ALIGN.CENTER)
    if i < 4:
        gx = x + BW
        arrow(s, gx + 0.06, SY + 0.28, GAPW - 0.12, PAPER_DIM, 1.0)
        # the gap is the finding — mark it
        mx = gx + GAPW / 2
        down_arrow(s, mx, SY + 0.62, 0.42, SIGNAL, 1.0)
        rect(s, mx - 0.92, SY + 1.06, 1.84, 0.62, None, SIGNAL_DIM, 0.9)
        text(s, mx - 0.86, SY + 1.15, 1.72, 0.46, gaps[i], size=9, font=MONO,
             color=SIGNAL, align=PP_ALIGN.CENTER, spacing=1.24)
    x += BW + GAPW

text(s, M, 6.36, 11.9, 0.4,
     [[("Four documents. Four different people. Often four different systems. ", {"color": PAPER_DIM}),
       ("Every gap is where money leaves.", {"color": SIGNAL})]],
     size=12.5, font=DISPLAY)


# ══════════════════════════════════════════════════════════════════════════
# 02 — PROPOSED SOLUTION
# ══════════════════════════════════════════════════════════════════════════
s = new_slide(2, "Proposed solution",
              "Read the whole corpus at once, then prove what you found.")

text(s, M, BODY_TOP, 7.6, 0.82,
     "LedgerLens ingests raw procurement records, resolves them into comparable "
     "entities, runs 42 deterministic and statistical detectors across the entire "
     "corpus, and returns findings that carry their own evidence and their own arithmetic.",
     size=13, color=PAPER_DIM, spacing=1.45)

# three movements
mv = [("RESOLVE", VERIFY, "Vendor entity resolution · SKU and unit normalisation · tax and currency alignment",
       "118 vendor records collapse to 96 real counterparties. 15 catalogue items absorb 47 raw description variants.",
       "Without this, every price comparison is a string comparison — and wrong."),
      ("DETECT", SIGNAL, "Rules engine (deterministic) → statistical models (robust z, Benford, Isolation Forest)",
       "42 detectors · 5 pillars · each a plugin emitting a typed Finding.",
       "The unit of analysis is the relationship between records, not the record."),
      ("ACT", GOLD, "Risk scoring → savings quantification → recommended action → drafted artifact",
       "163 findings · ₹18,42,650 identified · ₹6,21,400 already recovered.",
       "The language model writes the letter. It never writes the number.")]
x, CW = M, 3.82
for name, col, sub, detail, why in mv:
    rect(s, x, BODY_TOP + 0.92, CW, 2.68, PANEL, LINE, 0.9)
    rect(s, x, BODY_TOP + 0.92, 0.045, 2.68, col)
    text(s, x + 0.28, BODY_TOP + 1.12, CW - 0.5, 0.3, " ".join(name), size=10.5, font=MONO, color=col)
    text(s, x + 0.28, BODY_TOP + 1.50, CW - 0.52, 0.72, sub, size=10.5, color=PAPER, spacing=1.34)
    text(s, x + 0.28, BODY_TOP + 2.30, CW - 0.52, 0.66, detail, size=9.5, color=PAPER_DIM, spacing=1.32)
    hline(s, x + 0.28, BODY_TOP + 3.02, CW - 0.56, LINE, 0.7)
    text(s, x + 0.28, BODY_TOP + 3.14, CW - 0.52, 0.42, why, size=9, color=MUTED, spacing=1.3)
    if x + CW + 0.22 < W - M:
        arrow(s, x + CW + 0.04, BODY_TOP + 2.26, 0.18, MUTED, 1.0)
    x += CW + 0.22

# the line that survives the whole pitch
rect(s, M, 6.18, W - 2 * M, 0.82, None, GOLD_SOFT, 1.0)
text(s, M + 0.3, 6.32, 11.3, 0.32,
     "No language model ever produces a number in this system.", size=15, font=DISPLAY, color=GOLD)
text(s, M + 0.3, 6.68, 11.3, 0.28,
     "Rules and statistics compute. The model explains, drafts and translates. "
     "Every score is decomposable, reproducible and auditable to the rule that fired.",
     size=10, color=PAPER_DIM)


# ══════════════════════════════════════════════════════════════════════════
# 03 — FEATURES
# ══════════════════════════════════════════════════════════════════════════
s = new_slide(3, "Features", "Forty-two detectors. Seven working views. One evidence trail.")

pillars = [
    ("01", "Duplicates &\nOverpayment", 8, 41, 0.972, GOLD,
     "near-duplicate matching\ntransposition-tolerant numbers\ncross-alias duplicates"),
    ("02", "Price & Vendor\nIntelligence", 9, 38, 0.951, SLATE,
     "peer-median benchmarking\nprice-creep regression\nrate-card violation"),
    ("03", "Behavioural\nAnomalies", 11, 47, 0.908, SIGNAL,
     "PO splitting · threshold hugging\nBenford's Law\nIsolation Forest outliers"),
    ("04", "Vendor Integrity\n& Collusion", 8, 22, 0.964, CLAY,
     "shared-attribute rings\nvendor ↔ employee links\nbank change before payment"),
    ("05", "Compliance\n& Process", 6, 15, 0.981, VERIFY,
     "three-way match\nduplicate GST numbering\nMSME 45-day breach, s.43B(h)"),
]
x, CW = M, 2.28
for n, name, det, fnd, prec, col, flags in pillars:
    rect(s, x, BODY_TOP, CW, 2.86, PANEL, LINE, 0.9)
    rect(s, x, BODY_TOP, CW, 0.035, col)
    text(s, x + 0.2, BODY_TOP + 0.2, 1, 0.24, n, size=9, font=MONO, color=col)
    text(s, x + 0.2, BODY_TOP + 0.52, CW - 0.4, 0.7, name, size=12.5, color=PAPER, spacing=1.16)
    text(s, x + 0.2, BODY_TOP + 1.28, CW - 0.4, 0.28,
         [[(str(det), {"size": 17, "font": MONO, "color": col}),
           ("  detectors", {"size": 9, "color": MUTED})]])
    text(s, x + 0.2, BODY_TOP + 1.62, CW - 0.4, 0.44,
         f"{fnd} findings\n{prec*100:.1f}% precision", size=8.5, font=MONO, color=PAPER_DIM, spacing=1.28)
    hline(s, x + 0.2, BODY_TOP + 2.12, CW - 0.4, LINE, 0.7)
    text(s, x + 0.2, BODY_TOP + 2.24, CW - 0.4, 0.56, flags, size=8, color=MUTED, spacing=1.32)
    x += CW + 0.12

# the seven views
VY = BODY_TOP + 3.06
text(s, M, VY, 6, 0.26, " ".join("THE PRODUCT — SEVEN WORKING VIEWS"), size=8.5, font=MONO, color=MUTED)
views = [("Command Center", "hero figure, savings funnel, health index"),
         ("Findings Register", "sortable, filterable, 163 rows"),
         ("Evidence Drawer", "two documents side by side, fields diffed"),
         ("Price Intelligence", "peer median, creep, rate-card delta"),
         ("Vendor Integrity", "collusion graph, shared bank accounts"),
         ("Pattern Lab", "threshold histogram, Benford, off-hours"),
         ("Risk Score Studio", "live pillar weights, leaderboard reorders")]
x = M
for i, (nm, sub) in enumerate(views):
    cw = 1.63
    rect(s, x, VY + 0.32, cw, 0.78, PANEL2, LINE, 0.75)
    text(s, x + 0.13, VY + 0.44, cw - 0.26, 0.26, nm, size=9.5, color=PAPER)
    text(s, x + 0.13, VY + 0.66, cw - 0.26, 0.44, sub, size=7.5, color=MUTED, spacing=1.22)
    x += cw + 0.08

# the differentiating features, stated as capabilities not adjectives
FY = VY + 1.28
feats = [("Evidence, not alerts", "every finding opens the two source documents with matching and differing fields highlighted"),
         ("Drafted artifacts", "recovery email, commercial-review letter or audit-committee memo, typed from the finding"),
         ("Natural language + visible SQL", "the query is shown beneath the answer, so nothing can be hallucinated"),
         ("India compliance layer", "GSTIN format, duplicate GST numbering under Rule 46(b), HSN tax match, MSME s.43B(h)")]
x = M
for nm, sub in feats:
    vline(s, x, FY, 0.62, GOLD_SOFT, 1.3)
    text(s, x + 0.16, FY, 2.72, 0.26, nm, size=10, color=GOLD)
    text(s, x + 0.16, FY + 0.26, 2.72, 0.46, sub, size=8.5, color=PAPER_DIM, spacing=1.26)
    x += 2.98


# ══════════════════════════════════════════════════════════════════════════
# 04 — IDEA / APPROACH
# ══════════════════════════════════════════════════════════════════════════
s = new_slide(4, "Idea and approach", "Change the unit of analysis, and the fraud becomes visible.")

# left: the comparison that is the whole idea
text(s, M, BODY_TOP, 5.5, 0.28, " ".join("ONE RECORD AT A TIME"), size=8.5, font=MONO, color=MUTED)
rect(s, M, BODY_TOP + 0.34, 5.5, 1.24, PANEL, LINE, 0.9)
for i in range(5):
    bx = M + 0.26 + i * 1.02
    rect(s, bx, BODY_TOP + 0.56, 0.82, 0.5, PANEL2, LINE, 0.75)
    text(s, bx, BODY_TOP + 0.68, 0.82, 0.24, f"PO {i+1}", size=8.5, font=MONO,
         color=PAPER_DIM, align=PP_ALIGN.CENTER)
    text(s, bx, BODY_TOP + 1.12, 0.82, 0.24, "₹48,000", size=8, font=MONO,
         color=MUTED, align=PP_ALIGN.CENTER)
    text(s, bx, BODY_TOP + 1.34, 0.82, 0.2, "PASS", size=7.5, font=MONO,
         color=VERIFY, align=PP_ALIGN.CENTER)

text(s, M, BODY_TOP + 1.76, 5.5, 0.3,
     "Every one is below the ₹50,000 threshold. Every one is correctly approved. Nothing fires.",
     size=9.5, color=PAPER_DIM, spacing=1.3)

text(s, M, BODY_TOP + 2.32, 5.5, 0.28, " ".join("THE RELATIONSHIP BETWEEN THEM"), size=8.5, font=MONO, color=GOLD)
rect(s, M, BODY_TOP + 2.66, 5.5, 1.5, PANEL, SIGNAL_DIM, 1.0)
for i in range(5):
    bx = M + 0.26 + i * 1.02
    rect(s, bx, BODY_TOP + 2.86, 0.82, 0.42, PANEL2, SIGNAL, 0.75)
    text(s, bx, BODY_TOP + 2.95, 0.82, 0.24, f"PO {i+1}", size=8.5, font=MONO,
         color=SIGNAL, align=PP_ALIGN.CENTER)
    if i < 4:
        hline(s, bx + 0.82, BODY_TOP + 3.07, 0.2, SIGNAL, 1.0)
text(s, M + 0.26, BODY_TOP + 3.42, 5.0, 0.28,
     "one vendor · one 5-day window · each 96% of the limit", size=9, font=MONO, color=PAPER_DIM)
text(s, M + 0.26, BODY_TOP + 3.70, 5.0, 0.34,
     [[("₹2,40,000 routed around director approval", {"color": SIGNAL, "size": 12.5})]], font=MONO)

# right: the three method commitments
RX2 = 7.0
vline(s, RX2 - 0.4, BODY_TOP, 4.2, LINE, 0.9)
method = [("Resolution before comparison",
           "Vendor aliases and SKU variants are normalised first. “A4 PAPER 75GSM RM” and "
           "“Paper, A4, white, 75gsm” become one catalogue item before a single price is compared. "
           "Skip this and you are comparing strings and reporting noise."),
          ("Deterministic scoring, language-only LLM",
           "Rules and statistics compute every number. The model is confined to explanation, "
           "drafting and translation — the property that decides whether software like this is "
           "ever actually deployed."),
          ("Ground truth we planted ourselves",
           "A procurement fraud simulator injects 150 labelled frauds of known type into realistic "
           "spend. The engine then runs blind. That is what converts every claim on these slides "
           "from an assertion into a measurement.")]
yy = BODY_TOP
for i, (nm, body) in enumerate(method):
    text(s, RX2, yy, 0.5, 0.26, f"{i+1:02d}", size=9, font=MONO, color=GOLD)
    text(s, RX2 + 0.5, yy, 4.9, 0.28, nm, size=13, font=DISPLAY, color=PAPER)
    text(s, RX2 + 0.5, yy + 0.34, 4.86, 0.92, body, size=9.5, color=PAPER_DIM, spacing=1.4)
    yy += 1.42


# ══════════════════════════════════════════════════════════════════════════
# 05 — SYSTEM ARCHITECTURE / WORKFLOW
# ══════════════════════════════════════════════════════════════════════════
s = new_slide(5, "System architecture and workflow",
              "Four bands. A determinism boundary. One typed contract.")

BX, BW2 = M, 8.42          # architecture column
bands = [
    ("INGEST", SLATE,
     ["CSV", "Excel", "PDF", "Scanned image", "Email attachment"],
     "LLM schema mapper — any column naming survives contact"),
    ("RESOLVE", CLAY,
     ["Vendor entity resolution", "SKU + unit normalisation", "Currency & tax alignment"],
     "The prerequisite nobody builds — without it, no comparison is valid"),
    ("DETECT", SIGNAL,
     ["Rules engine (deterministic)", "Robust z · Benford", "Isolation Forest"],
     "42 detectors, plugin architecture, each emits a typed Finding"),
    ("ACT", GOLD,
     ["Risk scoring", "Savings quantification", "Recommended action", "Drafted artifact"],
     "LLM writes the language. It never writes the numbers"),
]
yy = BODY_TOP
BH = 0.92
for i, (name, col, comps, note) in enumerate(bands):
    rect(s, BX, yy, BW2, BH, PANEL, LINE, 0.9)
    rect(s, BX, yy, 0.045, BH, col)
    text(s, BX + 0.24, yy + 0.14, 1.5, 0.26, " ".join(name), size=10, font=MONO, color=col)
    # component boxes
    cx = BX + 1.72
    avail = BW2 - 1.94
    cw = (avail - 0.1 * (len(comps) - 1)) / len(comps)
    for c in comps:
        rect(s, cx, yy + 0.12, cw, 0.38, PANEL2, LINE, 0.75)
        text(s, cx + 0.06, yy + 0.215, cw - 0.12, 0.24, c, size=8.5, color=PAPER,
             align=PP_ALIGN.CENTER)
        cx += cw + 0.1
    text(s, BX + 0.24, yy + 0.72, 1.4, 0.24, "└─", size=9, font=MONO, color=MUTED)
    text(s, BX + 1.72, yy + 0.72, BW2 - 1.94, 0.28, note, size=9, color=PAPER_DIM)
    if i < len(bands) - 1:
        down_arrow(s, BX + 0.9, yy + BH + 0.015, 0.155, MUTED, 1.0)
    yy += BH + 0.19

# determinism boundary — drawn where it actually falls
by = BODY_TOP + 2 * (BH + 0.19) - 0.095
c = s.shapes.add_connector(MSO_CONNECTOR.STRAIGHT, Inches(BX - 0.18), Inches(by),
                           Inches(BX + BW2 + 0.18), Inches(by))
c.line.color.rgb = VERIFY; c.line.width = Pt(1.0); c.line.dash_style = 4
_noshadow(c)
text(s, BX + BW2 - 2.5, by - 0.235, 2.5, 0.24,
     "determinism boundary", size=8, font=MONO, color=VERIFY, align=PP_ALIGN.RIGHT)

# right rail — the contract every detector returns
RX3 = BX + BW2 + 0.42
text(s, RX3, BODY_TOP, 3.2, 0.3, " ".join("FINDING CONTRACT"), size=8.5, font=MONO, color=GOLD)
rect(s, RX3, BODY_TOP + 0.30, 2.98, 2.66, PANEL, LINE, 0.9)
code = ("interface Finding {\n"
        "  id: string\n"
        "  ruleId: string\n"
        "  pillar: Pillar\n"
        "  severity: Severity\n"
        "  entities: { invoiceIds,\n"
        "    vendorId, poIds? }\n"
        "  evidence: Record<\n"
        "    string, unknown>\n"
        "  moneyAtRisk: number\n"
        "  confidence: number\n"
        "  explanation: string\n"
        "  recommendedAction: Action\n"
        "  scoreContribution:\n"
        "    { component, points }[]\n"
        "}")
text(s, RX3 + 0.16, BODY_TOP + 0.42, 2.7, 2.4, code, size=7, font=MONO,
     color=PAPER_DIM, spacing=1.22)
text(s, RX3, BODY_TOP + 3.10, 2.98, 0.9,
     "Every detector is a plugin implementing run(ctx) => Finding[]. A new rule "
     "takes five minutes — which is why we can take a suggestion from this panel "
     "and demonstrate it before the session ends.",
     size=8, color=MUTED, spacing=1.34)

text(s, M, 6.42, 11.9, 0.3,
     [[("Runs fully offline. ", {"color": PAPER}),
       ("No backend, no network calls at runtime, seeded generation — the demo is "
        "byte-identical on every reload and cannot fail on venue wifi.", {"color": PAPER_DIM})]],
     size=10)


# ══════════════════════════════════════════════════════════════════════════
# 06 — INNOVATION & EXISTING SOLUTIONS
# ══════════════════════════════════════════════════════════════════════════
s = new_slide(6, "Innovation and existing solutions",
              "Written for a judge who has seen four similar demos today.")

rows = [("Unit of analysis", "one record at a time",
         "relationships across the whole corpus — the only place these frauds exist", True),
        ("Duplicate detection", "groupby(invoice_no).count() > 1",
         "fuzzy · transposition-tolerant · cross-alias · windowed on amount and date", False),
        ("Before comparing prices", "compares raw strings, silently wrong",
         "entity + SKU resolution first, or every price comparison is invalid", True),
        ("Risk score", "one opaque weighted sum",
         "five decomposable pillars, live weights, every point traced to a rule", False),
        ("Accuracy claim", "none possible",
         "87.5% precision / 98.0% recall against 150 planted frauds — measured, "
         "not asserted", True),
        ("Role of the LLM", "asked to judge the data",
         "forbidden from arithmetic — language only", False),
        ("Jurisdiction", "generic",
         "GSTIN checks, Rule 46(b) numbering, HSN tax match, MSME s.43B(h)", False),
        ("Extensibility", "rewrite the notebook",
         "plugin detector — new rule live in five minutes, on stage", False)]

TW, C1, C2 = 7.55, 2.05, 2.6
hy = BODY_TOP
text(s, M + C1, hy, C2, 0.24, " ".join("THE OBVIOUS BUILD"), size=8, font=MONO, color=MUTED)
text(s, M + C1 + C2 + 0.2, hy, 3.0, 0.24, " ".join("LEDGERLENS"), size=8, font=MONO, color=GOLD)
hy += 0.3
hline(s, M, hy, TW, LINE, 0.9)
hy += 0.06
for label, obv, ours, hero in rows:
    rh = 0.555
    if hero:
        rect(s, M + C1 + C2 + 0.12, hy, TW - C1 - C2 - 0.12, rh, PANEL, None)
    text(s, M, hy + 0.11, C1 - 0.1, 0.3, label, size=9.5, color=PAPER)
    text(s, M + C1, hy + 0.11, C2 - 0.14, 0.4, obv, size=8.5, font=MONO, color=MUTED, spacing=1.22)
    text(s, M + C1 + C2 + 0.22, hy + 0.11, TW - C1 - C2 - 0.34, 0.4, ours, size=8.5,
         color=(PAPER if hero else PAPER_DIM), spacing=1.22)
    hy += rh
    hline(s, M, hy, TW, LINE_SOFT, 0.6)

# right: where existing tools stop
RX4 = M + TW + 0.5
vline(s, RX4 - 0.28, BODY_TOP, 4.5, LINE, 0.9)
text(s, RX4, BODY_TOP, 4.0, 0.34, " ".join("WHERE EXISTING TOOLS STOP"), size=8.5, font=MONO, color=MUTED)
cats = [("ERP-native controls",
         "enforce policy at entry — a compliant PO that is one of five splitting a purchase is still compliant"),
        ("AP automation / invoice capture",
         "excellent at reading a document; the comparison set is that document"),
        ("Audit analytics suites",
         "run corpus-wide tests, but require an analyst to specify and interpret each one, per engagement"),
        ("Spend analytics dashboards",
         "aggregate to categories, which is exactly the operation that hides a pattern inside a total")]
yy = BODY_TOP + 0.36
for nm, why in cats:
    text(s, RX4, yy, 4.0, 0.26, nm, size=10, color=PAPER)
    text(s, RX4, yy + 0.25, 3.95, 0.5, why, size=8.5, color=MUTED, spacing=1.3)
    yy += 0.86

rect(s, RX4, yy + 0.06, 4.0, 0.86, None, GOLD_SOFT, 1.0)
text(s, RX4 + 0.18, yy + 0.2, 3.66, 0.62,
     "None of them is wrong. They are all built around a document. "
     "The frauds that cost the most do not live inside one.",
     size=10, font=DISPLAY, color=GOLD, spacing=1.3)


# ══════════════════════════════════════════════════════════════════════════
# 07 — IMPACT & FUTURE SCOPE
# ══════════════════════════════════════════════════════════════════════════
s = new_slide(7, "Impact and future scope",
              "Every rupee shown with the arithmetic that produced it.")

# ── the three tiers ──
text(s, M, BODY_TOP, 7.4, 0.26, " ".join("WHAT WAS FOUND, AND HOW IT WAS COMPUTED"), size=8.5, font=MONO, color=MUTED)
tiers = [("Recoverable", "₹8,42,650", "High", VERIFY,
          "11 confirmed duplicate pairs, already paid twice — the eleven amounts, summed"),
         ("Avoidable", "₹6,70,000", "Medium", GOLD,
          "Σ (unit price − peer median) × volume across 34 flagged SKU–vendor pairs"),
         ("Negotiable", "₹3,30,000", "Modelled", SLATE,
          "consolidation ₹2,18,000 + early-payment discounts not taken ₹1,12,000")]
yy = BODY_TOP + 0.34
for nm, amt, conf, col, basis in tiers:
    rect(s, M, yy, 7.4, 0.62, PANEL, LINE, 0.8)
    rect(s, M, yy, 0.035, 0.62, col)
    text(s, M + 0.22, yy + 0.09, 1.5, 0.26, nm, size=11, color=PAPER)
    text(s, M + 0.22, yy + 0.33, 5.0, 0.24, basis, size=8.5, color=MUTED)
    text(s, M + 5.42, yy + 0.15, 1.3, 0.3, amt, size=15, font=MONO, color=col, align=PP_ALIGN.RIGHT)
    text(s, M + 6.84, yy + 0.2, 0.5, 0.24, conf, size=7.5, font=MONO, color=MUTED, align=PP_ALIGN.RIGHT)
    yy += 0.68

rect(s, M, yy, 7.4, 0.72, PANEL2, GOLD_SOFT, 1.0)
text(s, M + 0.22, yy + 0.13, 3.4, 0.3, "Total identified", size=12, color=GOLD)
text(s, M + 0.22, yy + 0.4, 4.6, 0.24,
     "on ₹42.6 Cr analysed = 0.43% of spend", size=8.5, font=MONO, color=MUTED)
text(s, M + 4.6, yy + 0.16, 2.6, 0.4, "₹18,42,650", size=21, font=MONO, color=GOLD, align=PP_ALIGN.RIGHT)

# realization funnel — gold draining into green
FY2 = yy + 0.94
text(s, M, FY2, 7.4, 0.24, " ".join("REALIZATION — IDENTIFIED THROUGH TO CASH"), size=8, font=MONO, color=MUTED)
stages = [("Identified", 1842650, GOLD), ("Validated", 1120000, GOLD_SOFT),
          ("Actioned", 780000, SLATE), ("Recovered", 621400, VERIFY)]
fx = M
for i, (nm, val, col) in enumerate(stages):
    wfrac = val / 1842650
    bw = 1.62
    rect(s, fx, FY2 + 0.32, bw, 0.16, PANEL2, None)
    rect(s, fx, FY2 + 0.32, bw * wfrac, 0.16, col)
    text(s, fx, FY2 + 0.54, bw, 0.24, f"₹{val:,}".replace(",", ",")
         .replace("1,842,650", "18,42,650").replace("1,120,000", "11,20,000")
         .replace("780,000", "7,80,000").replace("621,400", "6,21,400"),
         size=9.5, font=MONO, color=col)
    text(s, fx, FY2 + 0.76, bw, 0.22, nm, size=8, color=MUTED)
    if i < 3:
        arrow(s, fx + bw + 0.02, FY2 + 0.40, 0.2, MUTED, 0.9)
    fx += bw + 0.22

# ── right rail: measured accuracy, and the weakness said out loud ──
RX5 = M + 7.9
vline(s, RX5 - 0.3, BODY_TOP, 4.6, LINE, 0.9)
text(s, RX5, BODY_TOP, 4.0, 0.26, " ".join("MEASURED, NOT ASSERTED"), size=8.5, font=MONO, color=MUTED)
mets = [("87.5%", "precision"), ("98.0%", "recall"), ("92.5%", "F1")]
mx = RX5
for v, k in mets:
    rect(s, mx, BODY_TOP + 0.32, 1.24, 0.78, PANEL, LINE, 0.8)
    text(s, mx, BODY_TOP + 0.44, 1.24, 0.32, v, size=17, font=MONO, color=VERIFY, align=PP_ALIGN.CENTER)
    text(s, mx, BODY_TOP + 0.80, 1.24, 0.24, k, size=8, font=MONO, color=MUTED, align=PP_ALIGN.CENTER)
    mx += 1.32
text(s, RX5, BODY_TOP + 1.20, 4.0, 0.60,
     "TP 147 · FP 21 · FN 3 · TN 1,358\n"
     "TP 147 + FN 3 = the 150 frauds we planted.\n"
     "python -m ledgerlens.eval.run",
     size=8.5, font=MONO, color=PAPER_DIM, spacing=1.34)

rect(s, RX5, BODY_TOP + 1.78, 4.0, 0.92, None, SIGNAL_DIM, 1.0)
text(s, RX5 + 0.16, BODY_TOP + 1.90, 3.7, 0.26, "Where we are weakest", size=9.5, color=SIGNAL)
text(s, RX5 + 0.16, BODY_TOP + 2.16, 3.7, 0.62,
     "Vendor Integrity is our least precise pillar at 77.8% — about one finding in five "
     "is an incidental attribute collision, not a relationship. We would rather show you "
     "that than round it away.",
     size=8.5, color=PAPER_DIM, spacing=1.3)

text(s, RX5, BODY_TOP + 2.80, 4.0, 0.26, " ".join("FUTURE SCOPE"), size=8.5, font=MONO, color=GOLD)
road = [("Tonight", "backend live on the real pipeline — the detectors already run headless"),
        ("This week", "OCR ingestion; the feedback loop that reweights a detector from analyst labels"),
        ("Production", "ERP connectors for Tally, SAP and Zoho · role-based access · tamper-evident, hash-chained audit log"),
        ("At scale", "0.43% of spend on this corpus. On a ₹500 Cr book, the same rate is ₹2.15 Cr a year")]
yy2 = BODY_TOP + 3.10
for w_, d in road:
    text(s, RX5, yy2, 0.9, 0.22, w_, size=8.5, font=MONO, color=GOLD)
    text(s, RX5 + 0.92, yy2, 3.08, 0.46, d, size=8.5, color=PAPER_DIM, spacing=1.26)
    yy2 += 0.5


# ══════════════════════════════════════════════════════════════════════════
# CLOSE
# ══════════════════════════════════════════════════════════════════════════
s = new_slide(bg="title")
text(s, M, 1.5, 5, 0.3, " ".join("LEDGERLENS"), size=11, font=MONO, color=GOLD)
text(s, M, 2.15, 10.6, 1.9,
     "Humans review invoices one at a time.\nThe problems only exist across thousands at once.",
     size=40, font=DISPLAY, color=PAPER, spacing=1.06)
hline(s, M, 4.5, W - 2 * M, LINE, 0.9)
cols = [("₹18,42,650", "recoverable, identified", GOLD),
        ("87.5% / 98.0%", "precision / recall, measured", VERIFY),
        ("42", "detectors, 5 pillars", PAPER),
        ("0", "numbers written by a language model", SIGNAL)]
x = M
for v, k, col in cols:
    text(s, x, 4.78, 2.9, 0.4, v, size=20, font=MONO, color=col)
    text(s, x, 5.2, 2.9, 0.3, k, size=9, color=MUTED)
    x += 2.98
text(s, M, 6.05, 10, 0.3,
     "Live prototype runs offline in the browser — no backend, no network, nothing to fail on stage.",
     size=11, color=PAPER_DIM)
text(s, M, 6.5, 10, 0.28, "Demo dataset — synthetic, generated for evaluation.",
     size=8.5, font=MONO, color=MUTED)

prs.save("LedgerLens_Deck.pptx")
print(f"saved LedgerLens_Deck.pptx — {len(prs.slides.__iter__.__self__._sldIdLst)} slides")
